"""remove unique for eth address

Revision ID: 22e390b7908a
Revises: 8690e2cc49ec
Create Date: 2018-02-20 15:35:18.334270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e390b7908a'
down_revision = '8690e2cc49ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_eth_tx_address', table_name='eth_tx')
    op.create_index(op.f('ix_eth_tx_address'), 'eth_tx', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eth_tx_address'), table_name='eth_tx')
    op.create_index('ix_eth_tx_address', 'eth_tx', ['address'], unique=1)
    # ### end Alembic commands ###
